#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_TTCMWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HAWContext")]
	public partial class DemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_color(tbl_color instance);
    partial void Updatetbl_color(tbl_color instance);
    partial void Deletetbl_color(tbl_color instance);
    partial void Inserttbl_state(tbl_state instance);
    partial void Updatetbl_state(tbl_state instance);
    partial void Deletetbl_state(tbl_state instance);
    partial void Inserttbl_Order(tbl_Order instance);
    partial void Updatetbl_Order(tbl_Order instance);
    partial void Deletetbl_Order(tbl_Order instance);
    partial void Inserttbl_user(tbl_user instance);
    partial void Updatetbl_user(tbl_user instance);
    partial void Deletetbl_user(tbl_user instance);
    partial void Inserttbl_product(tbl_product instance);
    partial void Updatetbl_product(tbl_product instance);
    partial void Deletetbl_product(tbl_product instance);
    partial void Inserttbl_producer(tbl_producer instance);
    partial void Updatetbl_producer(tbl_producer instance);
    partial void Deletetbl_producer(tbl_producer instance);
    partial void Inserttbl_category(tbl_category instance);
    partial void Updatetbl_category(tbl_category instance);
    partial void Deletetbl_category(tbl_category instance);
    #endregion
		
		public DemoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HAWContextConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_color> tbl_colors
		{
			get
			{
				return this.GetTable<tbl_color>();
			}
		}
		
		public System.Data.Linq.Table<tbl_state> tbl_states
		{
			get
			{
				return this.GetTable<tbl_state>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Order> tbl_Orders
		{
			get
			{
				return this.GetTable<tbl_Order>();
			}
		}
		
		public System.Data.Linq.Table<tbl_user> tbl_users
		{
			get
			{
				return this.GetTable<tbl_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_product> tbl_products
		{
			get
			{
				return this.GetTable<tbl_product>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producer> tbl_producers
		{
			get
			{
				return this.GetTable<tbl_producer>();
			}
		}
		
		public System.Data.Linq.Table<tbl_category> tbl_categories
		{
			get
			{
				return this.GetTable<tbl_category>();
			}
		}
		
		public System.Data.Linq.Table<producer> producers
		{
			get
			{
				return this.GetTable<producer>();
			}
		}
		
		public System.Data.Linq.Table<order1> order1s
		{
			get
			{
				return this.GetTable<order1>();
			}
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_color")]
	public partial class tbl_color : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _color_id;
		
		private string _color_name;
		
		private string _color_img;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncolor_idChanging(int value);
    partial void Oncolor_idChanged();
    partial void Oncolor_nameChanging(string value);
    partial void Oncolor_nameChanged();
    partial void Oncolor_imgChanging(string value);
    partial void Oncolor_imgChanged();
    #endregion
		
		public tbl_color()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int color_id
		{
			get
			{
				return this._color_id;
			}
			set
			{
				if ((this._color_id != value))
				{
					this.Oncolor_idChanging(value);
					this.SendPropertyChanging();
					this._color_id = value;
					this.SendPropertyChanged("color_id");
					this.Oncolor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_name", DbType="NVarChar(255)")]
		public string color_name
		{
			get
			{
				return this._color_name;
			}
			set
			{
				if ((this._color_name != value))
				{
					this.Oncolor_nameChanging(value);
					this.SendPropertyChanging();
					this._color_name = value;
					this.SendPropertyChanged("color_name");
					this.Oncolor_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_img", DbType="NVarChar(255)")]
		public string color_img
		{
			get
			{
				return this._color_img;
			}
			set
			{
				if ((this._color_img != value))
				{
					this.Oncolor_imgChanging(value);
					this.SendPropertyChanging();
					this._color_img = value;
					this.SendPropertyChanged("color_img");
					this.Oncolor_imgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_state")]
	public partial class tbl_state : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _state_id;
		
		private string _state_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstate_idChanging(int value);
    partial void Onstate_idChanged();
    partial void Onstate_nameChanging(string value);
    partial void Onstate_nameChanged();
    #endregion
		
		public tbl_state()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int state_id
		{
			get
			{
				return this._state_id;
			}
			set
			{
				if ((this._state_id != value))
				{
					this.Onstate_idChanging(value);
					this.SendPropertyChanging();
					this._state_id = value;
					this.SendPropertyChanged("state_id");
					this.Onstate_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this.Onstate_nameChanging(value);
					this.SendPropertyChanging();
					this._state_name = value;
					this.SendPropertyChanged("state_name");
					this.Onstate_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Order")]
	public partial class tbl_Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private System.Nullable<int> _user_id;
		
		private string _order_receiver_note;
		
		private System.Nullable<double> _order_total_price;
		
		private System.Nullable<int> _order_state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onorder_receiver_noteChanging(string value);
    partial void Onorder_receiver_noteChanged();
    partial void Onorder_total_priceChanging(System.Nullable<double> value);
    partial void Onorder_total_priceChanged();
    partial void Onorder_stateChanging(System.Nullable<int> value);
    partial void Onorder_stateChanged();
    #endregion
		
		public tbl_Order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_receiver_note", DbType="NVarChar(255)")]
		public string order_receiver_note
		{
			get
			{
				return this._order_receiver_note;
			}
			set
			{
				if ((this._order_receiver_note != value))
				{
					this.Onorder_receiver_noteChanging(value);
					this.SendPropertyChanging();
					this._order_receiver_note = value;
					this.SendPropertyChanged("order_receiver_note");
					this.Onorder_receiver_noteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total_price", DbType="Float")]
		public System.Nullable<double> order_total_price
		{
			get
			{
				return this._order_total_price;
			}
			set
			{
				if ((this._order_total_price != value))
				{
					this.Onorder_total_priceChanging(value);
					this.SendPropertyChanging();
					this._order_total_price = value;
					this.SendPropertyChanged("order_total_price");
					this.Onorder_total_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_state", DbType="Int")]
		public System.Nullable<int> order_state
		{
			get
			{
				return this._order_state;
			}
			set
			{
				if ((this._order_state != value))
				{
					this.Onorder_stateChanging(value);
					this.SendPropertyChanging();
					this._order_state = value;
					this.SendPropertyChanged("order_state");
					this.Onorder_stateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_user")]
	public partial class tbl_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _user_email;
		
		private string _user_phone;
		
		private string _user_address;
		
		private string _user_password;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private bool _isActive;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<int> _question_id;
		
		private string _answer;
		
		private string _remember_me_identify;
		
		private string _remember_me_token;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_phoneChanging(string value);
    partial void Onuser_phoneChanged();
    partial void Onuser_addressChanging(string value);
    partial void Onuser_addressChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnisActiveChanging(bool value);
    partial void OnisActiveChanged();
    partial void OntimeChanging(System.Nullable<System.DateTime> value);
    partial void OntimeChanged();
    partial void Onquestion_idChanging(System.Nullable<int> value);
    partial void Onquestion_idChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    partial void Onremember_me_identifyChanging(string value);
    partial void Onremember_me_identifyChanged();
    partial void Onremember_me_tokenChanging(string value);
    partial void Onremember_me_tokenChanged();
    #endregion
		
		public tbl_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="NVarChar(255)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phone", DbType="NVarChar(11)")]
		public string user_phone
		{
			get
			{
				return this._user_phone;
			}
			set
			{
				if ((this._user_phone != value))
				{
					this.Onuser_phoneChanging(value);
					this.SendPropertyChanging();
					this._user_phone = value;
					this.SendPropertyChanged("user_phone");
					this.Onuser_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_address", DbType="NVarChar(500)")]
		public string user_address
		{
			get
			{
				return this._user_address;
			}
			set
			{
				if ((this._user_address != value))
				{
					this.Onuser_addressChanging(value);
					this.SendPropertyChanging();
					this._user_address = value;
					this.SendPropertyChanged("user_address");
					this.Onuser_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="NVarChar(255)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit NOT NULL")]
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Date")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="Int")]
		public System.Nullable<int> question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this.Onquestion_idChanging(value);
					this.SendPropertyChanging();
					this._question_id = value;
					this.SendPropertyChanged("question_id");
					this.Onquestion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="NVarChar(500)")]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this.OnanswerChanging(value);
					this.SendPropertyChanging();
					this._answer = value;
					this.SendPropertyChanged("answer");
					this.OnanswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_me_identify", DbType="NVarChar(500)")]
		public string remember_me_identify
		{
			get
			{
				return this._remember_me_identify;
			}
			set
			{
				if ((this._remember_me_identify != value))
				{
					this.Onremember_me_identifyChanging(value);
					this.SendPropertyChanging();
					this._remember_me_identify = value;
					this.SendPropertyChanged("remember_me_identify");
					this.Onremember_me_identifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_me_token", DbType="NVarChar(255)")]
		public string remember_me_token
		{
			get
			{
				return this._remember_me_token;
			}
			set
			{
				if ((this._remember_me_token != value))
				{
					this.Onremember_me_tokenChanging(value);
					this.SendPropertyChanging();
					this._remember_me_token = value;
					this.SendPropertyChanged("remember_me_token");
					this.Onremember_me_tokenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_product")]
	public partial class tbl_product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_id;
		
		private string _product_name;
		
		private string _product_alias;
		
		private string _product_description;
		
		private string _product_content;
		
		private string _product_img;
		
		private string _product_sub_img;
		
		private System.Nullable<bool> _product_isHot;
		
		private System.Nullable<bool> _product_isNew;
		
		private System.Nullable<bool> _product_isSale;
		
		private System.Nullable<System.DateTime> _product_CreatedAt;
		
		private System.Nullable<System.DateTime> _product_UpdatedAt;
		
		private string _product_code;
		
		private string _product_package;
		
		private string _product_delivery;
		
		private System.Nullable<System.DateTime> _product_delivery_time;
		
		private string _product_payment;
		
		private string _product_payment_type;
		
		private string _product_sub_info;
		
		private System.Nullable<int> _state;
		
		private string _title_seo;
		
		private string _des_seo;
		
		private string _friendly_url;
		
		private string _keyword;
		
		private string _product_material;
		
		private string _product_shape;
		
		private System.Nullable<int> _product_producer;
		
		private System.Nullable<int> _category_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_aliasChanging(string value);
    partial void Onproduct_aliasChanged();
    partial void Onproduct_descriptionChanging(string value);
    partial void Onproduct_descriptionChanged();
    partial void Onproduct_contentChanging(string value);
    partial void Onproduct_contentChanged();
    partial void Onproduct_imgChanging(string value);
    partial void Onproduct_imgChanged();
    partial void Onproduct_sub_imgChanging(string value);
    partial void Onproduct_sub_imgChanged();
    partial void Onproduct_isHotChanging(System.Nullable<bool> value);
    partial void Onproduct_isHotChanged();
    partial void Onproduct_isNewChanging(System.Nullable<bool> value);
    partial void Onproduct_isNewChanged();
    partial void Onproduct_isSaleChanging(System.Nullable<bool> value);
    partial void Onproduct_isSaleChanged();
    partial void Onproduct_CreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void Onproduct_CreatedAtChanged();
    partial void Onproduct_UpdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void Onproduct_UpdatedAtChanged();
    partial void Onproduct_codeChanging(string value);
    partial void Onproduct_codeChanged();
    partial void Onproduct_packageChanging(string value);
    partial void Onproduct_packageChanged();
    partial void Onproduct_deliveryChanging(string value);
    partial void Onproduct_deliveryChanged();
    partial void Onproduct_delivery_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onproduct_delivery_timeChanged();
    partial void Onproduct_paymentChanging(string value);
    partial void Onproduct_paymentChanged();
    partial void Onproduct_payment_typeChanging(string value);
    partial void Onproduct_payment_typeChanged();
    partial void Onproduct_sub_infoChanging(string value);
    partial void Onproduct_sub_infoChanged();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    partial void Ontitle_seoChanging(string value);
    partial void Ontitle_seoChanged();
    partial void Ondes_seoChanging(string value);
    partial void Ondes_seoChanged();
    partial void Onfriendly_urlChanging(string value);
    partial void Onfriendly_urlChanged();
    partial void OnkeywordChanging(string value);
    partial void OnkeywordChanged();
    partial void Onproduct_materialChanging(string value);
    partial void Onproduct_materialChanged();
    partial void Onproduct_shapeChanging(string value);
    partial void Onproduct_shapeChanged();
    partial void Onproduct_producerChanging(System.Nullable<int> value);
    partial void Onproduct_producerChanged();
    partial void Oncategory_idChanging(System.Nullable<int> value);
    partial void Oncategory_idChanged();
    #endregion
		
		public tbl_product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_alias", DbType="NVarChar(255)")]
		public string product_alias
		{
			get
			{
				return this._product_alias;
			}
			set
			{
				if ((this._product_alias != value))
				{
					this.Onproduct_aliasChanging(value);
					this.SendPropertyChanging();
					this._product_alias = value;
					this.SendPropertyChanged("product_alias");
					this.Onproduct_aliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_description", DbType="NVarChar(255)")]
		public string product_description
		{
			get
			{
				return this._product_description;
			}
			set
			{
				if ((this._product_description != value))
				{
					this.Onproduct_descriptionChanging(value);
					this.SendPropertyChanging();
					this._product_description = value;
					this.SendPropertyChanged("product_description");
					this.Onproduct_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_content", DbType="NVarChar(255)")]
		public string product_content
		{
			get
			{
				return this._product_content;
			}
			set
			{
				if ((this._product_content != value))
				{
					this.Onproduct_contentChanging(value);
					this.SendPropertyChanging();
					this._product_content = value;
					this.SendPropertyChanged("product_content");
					this.Onproduct_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_img", DbType="NVarChar(255)")]
		public string product_img
		{
			get
			{
				return this._product_img;
			}
			set
			{
				if ((this._product_img != value))
				{
					this.Onproduct_imgChanging(value);
					this.SendPropertyChanging();
					this._product_img = value;
					this.SendPropertyChanged("product_img");
					this.Onproduct_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sub_img", DbType="NVarChar(255)")]
		public string product_sub_img
		{
			get
			{
				return this._product_sub_img;
			}
			set
			{
				if ((this._product_sub_img != value))
				{
					this.Onproduct_sub_imgChanging(value);
					this.SendPropertyChanging();
					this._product_sub_img = value;
					this.SendPropertyChanged("product_sub_img");
					this.Onproduct_sub_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isHot", DbType="Bit")]
		public System.Nullable<bool> product_isHot
		{
			get
			{
				return this._product_isHot;
			}
			set
			{
				if ((this._product_isHot != value))
				{
					this.Onproduct_isHotChanging(value);
					this.SendPropertyChanging();
					this._product_isHot = value;
					this.SendPropertyChanged("product_isHot");
					this.Onproduct_isHotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isNew", DbType="Bit")]
		public System.Nullable<bool> product_isNew
		{
			get
			{
				return this._product_isNew;
			}
			set
			{
				if ((this._product_isNew != value))
				{
					this.Onproduct_isNewChanging(value);
					this.SendPropertyChanging();
					this._product_isNew = value;
					this.SendPropertyChanged("product_isNew");
					this.Onproduct_isNewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isSale", DbType="Bit")]
		public System.Nullable<bool> product_isSale
		{
			get
			{
				return this._product_isSale;
			}
			set
			{
				if ((this._product_isSale != value))
				{
					this.Onproduct_isSaleChanging(value);
					this.SendPropertyChanging();
					this._product_isSale = value;
					this.SendPropertyChanged("product_isSale");
					this.Onproduct_isSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_CreatedAt
		{
			get
			{
				return this._product_CreatedAt;
			}
			set
			{
				if ((this._product_CreatedAt != value))
				{
					this.Onproduct_CreatedAtChanging(value);
					this.SendPropertyChanging();
					this._product_CreatedAt = value;
					this.SendPropertyChanged("product_CreatedAt");
					this.Onproduct_CreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_UpdatedAt
		{
			get
			{
				return this._product_UpdatedAt;
			}
			set
			{
				if ((this._product_UpdatedAt != value))
				{
					this.Onproduct_UpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._product_UpdatedAt = value;
					this.SendPropertyChanged("product_UpdatedAt");
					this.Onproduct_UpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_code", DbType="NVarChar(255)")]
		public string product_code
		{
			get
			{
				return this._product_code;
			}
			set
			{
				if ((this._product_code != value))
				{
					this.Onproduct_codeChanging(value);
					this.SendPropertyChanging();
					this._product_code = value;
					this.SendPropertyChanged("product_code");
					this.Onproduct_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_package", DbType="NVarChar(255)")]
		public string product_package
		{
			get
			{
				return this._product_package;
			}
			set
			{
				if ((this._product_package != value))
				{
					this.Onproduct_packageChanging(value);
					this.SendPropertyChanging();
					this._product_package = value;
					this.SendPropertyChanged("product_package");
					this.Onproduct_packageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_delivery", DbType="NVarChar(255)")]
		public string product_delivery
		{
			get
			{
				return this._product_delivery;
			}
			set
			{
				if ((this._product_delivery != value))
				{
					this.Onproduct_deliveryChanging(value);
					this.SendPropertyChanging();
					this._product_delivery = value;
					this.SendPropertyChanged("product_delivery");
					this.Onproduct_deliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_delivery_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_delivery_time
		{
			get
			{
				return this._product_delivery_time;
			}
			set
			{
				if ((this._product_delivery_time != value))
				{
					this.Onproduct_delivery_timeChanging(value);
					this.SendPropertyChanging();
					this._product_delivery_time = value;
					this.SendPropertyChanged("product_delivery_time");
					this.Onproduct_delivery_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_payment", DbType="NVarChar(255)")]
		public string product_payment
		{
			get
			{
				return this._product_payment;
			}
			set
			{
				if ((this._product_payment != value))
				{
					this.Onproduct_paymentChanging(value);
					this.SendPropertyChanging();
					this._product_payment = value;
					this.SendPropertyChanged("product_payment");
					this.Onproduct_paymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_payment_type", DbType="NVarChar(255)")]
		public string product_payment_type
		{
			get
			{
				return this._product_payment_type;
			}
			set
			{
				if ((this._product_payment_type != value))
				{
					this.Onproduct_payment_typeChanging(value);
					this.SendPropertyChanging();
					this._product_payment_type = value;
					this.SendPropertyChanged("product_payment_type");
					this.Onproduct_payment_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sub_info", DbType="NVarChar(255)")]
		public string product_sub_info
		{
			get
			{
				return this._product_sub_info;
			}
			set
			{
				if ((this._product_sub_info != value))
				{
					this.Onproduct_sub_infoChanging(value);
					this.SendPropertyChanging();
					this._product_sub_info = value;
					this.SendPropertyChanged("product_sub_info");
					this.Onproduct_sub_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title_seo", DbType="NVarChar(255)")]
		public string title_seo
		{
			get
			{
				return this._title_seo;
			}
			set
			{
				if ((this._title_seo != value))
				{
					this.Ontitle_seoChanging(value);
					this.SendPropertyChanging();
					this._title_seo = value;
					this.SendPropertyChanged("title_seo");
					this.Ontitle_seoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_seo", DbType="NVarChar(255)")]
		public string des_seo
		{
			get
			{
				return this._des_seo;
			}
			set
			{
				if ((this._des_seo != value))
				{
					this.Ondes_seoChanging(value);
					this.SendPropertyChanging();
					this._des_seo = value;
					this.SendPropertyChanged("des_seo");
					this.Ondes_seoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendly_url", DbType="NVarChar(255)")]
		public string friendly_url
		{
			get
			{
				return this._friendly_url;
			}
			set
			{
				if ((this._friendly_url != value))
				{
					this.Onfriendly_urlChanging(value);
					this.SendPropertyChanging();
					this._friendly_url = value;
					this.SendPropertyChanged("friendly_url");
					this.Onfriendly_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="NVarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this.OnkeywordChanging(value);
					this.SendPropertyChanging();
					this._keyword = value;
					this.SendPropertyChanged("keyword");
					this.OnkeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_material", DbType="NVarChar(255)")]
		public string product_material
		{
			get
			{
				return this._product_material;
			}
			set
			{
				if ((this._product_material != value))
				{
					this.Onproduct_materialChanging(value);
					this.SendPropertyChanging();
					this._product_material = value;
					this.SendPropertyChanged("product_material");
					this.Onproduct_materialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_shape", DbType="NVarChar(255)")]
		public string product_shape
		{
			get
			{
				return this._product_shape;
			}
			set
			{
				if ((this._product_shape != value))
				{
					this.Onproduct_shapeChanging(value);
					this.SendPropertyChanging();
					this._product_shape = value;
					this.SendPropertyChanged("product_shape");
					this.Onproduct_shapeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_producer", DbType="Int")]
		public System.Nullable<int> product_producer
		{
			get
			{
				return this._product_producer;
			}
			set
			{
				if ((this._product_producer != value))
				{
					this.Onproduct_producerChanging(value);
					this.SendPropertyChanging();
					this._product_producer = value;
					this.SendPropertyChanged("product_producer");
					this.Onproduct_producerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int")]
		public System.Nullable<int> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producer")]
	public partial class tbl_producer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _producer_id;
		
		private string _producer_name;
		
		private string _producer_address;
		
		private System.Nullable<int> _state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproducer_idChanging(int value);
    partial void Onproducer_idChanged();
    partial void Onproducer_nameChanging(string value);
    partial void Onproducer_nameChanged();
    partial void Onproducer_addressChanging(string value);
    partial void Onproducer_addressChanged();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    #endregion
		
		public tbl_producer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int producer_id
		{
			get
			{
				return this._producer_id;
			}
			set
			{
				if ((this._producer_id != value))
				{
					this.Onproducer_idChanging(value);
					this.SendPropertyChanging();
					this._producer_id = value;
					this.SendPropertyChanged("producer_id");
					this.Onproducer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_name", DbType="NVarChar(255)")]
		public string producer_name
		{
			get
			{
				return this._producer_name;
			}
			set
			{
				if ((this._producer_name != value))
				{
					this.Onproducer_nameChanging(value);
					this.SendPropertyChanging();
					this._producer_name = value;
					this.SendPropertyChanged("producer_name");
					this.Onproducer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_address", DbType="NVarChar(255)")]
		public string producer_address
		{
			get
			{
				return this._producer_address;
			}
			set
			{
				if ((this._producer_address != value))
				{
					this.Onproducer_addressChanging(value);
					this.SendPropertyChanging();
					this._producer_address = value;
					this.SendPropertyChanged("producer_address");
					this.Onproducer_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_category")]
	public partial class tbl_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _category_id;
		
		private string _category_name;
		
		private string _category_parent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void Oncategory_nameChanging(string value);
    partial void Oncategory_nameChanged();
    partial void Oncategory_parentChanging(string value);
    partial void Oncategory_parentChanged();
    #endregion
		
		public tbl_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(255)")]
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				if ((this._category_name != value))
				{
					this.Oncategory_nameChanging(value);
					this.SendPropertyChanging();
					this._category_name = value;
					this.SendPropertyChanged("category_name");
					this.Oncategory_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_parent", DbType="NVarChar(255)")]
		public string category_parent
		{
			get
			{
				return this._category_parent;
			}
			set
			{
				if ((this._category_parent != value))
				{
					this.Oncategory_parentChanging(value);
					this.SendPropertyChanging();
					this._category_parent = value;
					this.SendPropertyChanged("category_parent");
					this.Oncategory_parentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producer")]
	public partial class producer
	{
		
		private int _producer_id;
		
		private string _producer_name;
		
		private string _producer_address;
		
		private System.Nullable<int> _state;
		
		private string _state_name;
		
		public producer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_id", DbType="Int NOT NULL")]
		public int producer_id
		{
			get
			{
				return this._producer_id;
			}
			set
			{
				if ((this._producer_id != value))
				{
					this._producer_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_name", DbType="NVarChar(255)")]
		public string producer_name
		{
			get
			{
				return this._producer_name;
			}
			set
			{
				if ((this._producer_name != value))
				{
					this._producer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_address", DbType="NVarChar(255)")]
		public string producer_address
		{
			get
			{
				return this._producer_address;
			}
			set
			{
				if ((this._producer_address != value))
				{
					this._producer_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order1")]
	public partial class order1
	{
		
		private int _order_id;
		
		private int _user_id;
		
		private string _user_name;
		
		private string _order_receiver_note;
		
		private System.Nullable<double> _order_total_price;
		
		private int _state_id;
		
		private string _state_name;
		
		public order1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL")]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(255)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_receiver_note", DbType="NVarChar(255)")]
		public string order_receiver_note
		{
			get
			{
				return this._order_receiver_note;
			}
			set
			{
				if ((this._order_receiver_note != value))
				{
					this._order_receiver_note = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total_price", DbType="Float")]
		public System.Nullable<double> order_total_price
		{
			get
			{
				return this._order_total_price;
			}
			set
			{
				if ((this._order_total_price != value))
				{
					this._order_total_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_id", DbType="Int NOT NULL")]
		public int state_id
		{
			get
			{
				return this._state_id;
			}
			set
			{
				if ((this._state_id != value))
				{
					this._state_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class product
	{
		
		private int _product_id;
		
		private string _product_name;
		
		private string _product_alias;
		
		private string _product_description;
		
		private string _product_content;
		
		private string _product_img;
		
		private string _product_sub_img;
		
		private System.Nullable<bool> _product_isHot;
		
		private System.Nullable<bool> _product_isNew;
		
		private System.Nullable<bool> _product_isSale;
		
		private System.Nullable<System.DateTime> _product_CreatedAt;
		
		private System.Nullable<System.DateTime> _product_UpdatedAt;
		
		private string _product_code;
		
		private string _product_package;
		
		private string _product_delivery;
		
		private System.Nullable<System.DateTime> _product_delivery_time;
		
		private string _product_payment;
		
		private string _product_payment_type;
		
		private System.Nullable<int> _state;
		
		private string _state_name;
		
		private string _title_seo;
		
		private string _des_seo;
		
		private string _friendly_url;
		
		private string _keyword;
		
		private string _product_material;
		
		private string _product_shape;
		
		private System.Nullable<int> _product_producer;
		
		private string _producer_name;
		
		private int _category_id;
		
		private string _category_name;
		
		public product()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this._product_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this._product_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_alias", DbType="NVarChar(255)")]
		public string product_alias
		{
			get
			{
				return this._product_alias;
			}
			set
			{
				if ((this._product_alias != value))
				{
					this._product_alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_description", DbType="NVarChar(255)")]
		public string product_description
		{
			get
			{
				return this._product_description;
			}
			set
			{
				if ((this._product_description != value))
				{
					this._product_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_content", DbType="NVarChar(255)")]
		public string product_content
		{
			get
			{
				return this._product_content;
			}
			set
			{
				if ((this._product_content != value))
				{
					this._product_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_img", DbType="NVarChar(255)")]
		public string product_img
		{
			get
			{
				return this._product_img;
			}
			set
			{
				if ((this._product_img != value))
				{
					this._product_img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_sub_img", DbType="NVarChar(255)")]
		public string product_sub_img
		{
			get
			{
				return this._product_sub_img;
			}
			set
			{
				if ((this._product_sub_img != value))
				{
					this._product_sub_img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isHot", DbType="Bit")]
		public System.Nullable<bool> product_isHot
		{
			get
			{
				return this._product_isHot;
			}
			set
			{
				if ((this._product_isHot != value))
				{
					this._product_isHot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isNew", DbType="Bit")]
		public System.Nullable<bool> product_isNew
		{
			get
			{
				return this._product_isNew;
			}
			set
			{
				if ((this._product_isNew != value))
				{
					this._product_isNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_isSale", DbType="Bit")]
		public System.Nullable<bool> product_isSale
		{
			get
			{
				return this._product_isSale;
			}
			set
			{
				if ((this._product_isSale != value))
				{
					this._product_isSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_CreatedAt
		{
			get
			{
				return this._product_CreatedAt;
			}
			set
			{
				if ((this._product_CreatedAt != value))
				{
					this._product_CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_UpdatedAt
		{
			get
			{
				return this._product_UpdatedAt;
			}
			set
			{
				if ((this._product_UpdatedAt != value))
				{
					this._product_UpdatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_code", DbType="NVarChar(255)")]
		public string product_code
		{
			get
			{
				return this._product_code;
			}
			set
			{
				if ((this._product_code != value))
				{
					this._product_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_package", DbType="NVarChar(255)")]
		public string product_package
		{
			get
			{
				return this._product_package;
			}
			set
			{
				if ((this._product_package != value))
				{
					this._product_package = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_delivery", DbType="NVarChar(255)")]
		public string product_delivery
		{
			get
			{
				return this._product_delivery;
			}
			set
			{
				if ((this._product_delivery != value))
				{
					this._product_delivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_delivery_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> product_delivery_time
		{
			get
			{
				return this._product_delivery_time;
			}
			set
			{
				if ((this._product_delivery_time != value))
				{
					this._product_delivery_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_payment", DbType="NVarChar(255)")]
		public string product_payment
		{
			get
			{
				return this._product_payment;
			}
			set
			{
				if ((this._product_payment != value))
				{
					this._product_payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_payment_type", DbType="NVarChar(255)")]
		public string product_payment_type
		{
			get
			{
				return this._product_payment_type;
			}
			set
			{
				if ((this._product_payment_type != value))
				{
					this._product_payment_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="NVarChar(255)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this._state_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title_seo", DbType="NVarChar(255)")]
		public string title_seo
		{
			get
			{
				return this._title_seo;
			}
			set
			{
				if ((this._title_seo != value))
				{
					this._title_seo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des_seo", DbType="NVarChar(255)")]
		public string des_seo
		{
			get
			{
				return this._des_seo;
			}
			set
			{
				if ((this._des_seo != value))
				{
					this._des_seo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendly_url", DbType="NVarChar(255)")]
		public string friendly_url
		{
			get
			{
				return this._friendly_url;
			}
			set
			{
				if ((this._friendly_url != value))
				{
					this._friendly_url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="NVarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this._keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_material", DbType="NVarChar(255)")]
		public string product_material
		{
			get
			{
				return this._product_material;
			}
			set
			{
				if ((this._product_material != value))
				{
					this._product_material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_shape", DbType="NVarChar(255)")]
		public string product_shape
		{
			get
			{
				return this._product_shape;
			}
			set
			{
				if ((this._product_shape != value))
				{
					this._product_shape = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_producer", DbType="Int")]
		public System.Nullable<int> product_producer
		{
			get
			{
				return this._product_producer;
			}
			set
			{
				if ((this._product_producer != value))
				{
					this._product_producer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producer_name", DbType="NVarChar(255)")]
		public string producer_name
		{
			get
			{
				return this._producer_name;
			}
			set
			{
				if ((this._producer_name != value))
				{
					this._producer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this._category_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(255)")]
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				if ((this._category_name != value))
				{
					this._category_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
